#!/usr/bin/env sh

# Guide for suport color in sh
# https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux
white=$'\e[0m'
green=$'\e[1;32m'
red=$'\e[1;31m'
cyan=$'\e[0;36m'
yellow=$'\e[1;33m'

gitf=".git"
head="$gitf/HEAD"
heads="$gitf/refs/heads"
rheads="ref: refs/heads"

okfn () {
  echo $green"OK"$white
  exit 0
}

warnfn() {
  echo $yellow"WARN"$white" $1"
}

failfn () {
  echo $red"FAIL"$white
  exit $1
}

import lib/add.sh
import lib/branch.sh
import lib/commit.sh
import lib/init.sh

args=($@)
$1 ${args[@]:1}
